import { Sparkles, Send, BookOpen, ListChecks, Lightbulb, Route, BarChart3, Plus } from 'lucide-react';
import { useState } from 'react';

const actions = [[BookOpen, 'Explain this concept', 'Break a topic into clear steps'], [ListChecks, 'Generate questions', 'Practice what you just learned'], [Lightbulb, 'Give me a hint', 'Get unstuck without the answer'], [Route, 'Create a study plan', 'Build a plan around your time'], [BarChart3, 'Analyze my mistakes', 'Find patterns in your attempts']];

export default function AIAssistantPage() {
  const [text, setText] = useState(''); const [messages, setMessages] = useState([]);
  const send = (e) => { e.preventDefault(); if (!text.trim()) return; setMessages((m) => [...m, { user: true, text }, { text: 'I can help you build a mental model for that. Start by identifying the inputs, the state that changes, and the outcome you need to reason about.' }]); setText(''); };
  return <div className="mx-auto grid max-w-6xl gap-6 pb-10 lg:grid-cols-[290px_1fr]"><aside className="rounded-2xl bg-slate-950 p-5 text-white"><div className="flex items-center gap-2"><span className="grid h-9 w-9 place-items-center rounded-xl bg-indigo-500"><Sparkles size={18}/></span><div><b className="text-sm">Study intelligence</b><p className="text-xs text-slate-400">Personalized for you</p></div></div><button className="mt-7 flex w-full items-center gap-2 rounded-xl bg-white/10 px-3 py-2.5 text-sm font-semibold hover:bg-white/15"><Plus size={16}/> New learning thread</button><div className="mt-7"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-slate-500">Recent</p>{['Operating System scheduling','DBMS normalization revision','GATE weekly plan'].map((item) => <button key={item} className="mt-2 w-full rounded-lg px-2 py-2 text-left text-xs text-slate-300 hover:bg-white/10">{item}</button>)}</div></aside><section className="min-h-[620px] overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><header className="border-b border-slate-100 px-6 py-5"><p className="text-xs font-bold uppercase tracking-[.18em] text-indigo-600">AI study assistant</p><h1 className="mt-1 text-2xl font-extrabold tracking-[-.04em] text-slate-900">Learn faster. Understand deeper.</h1></header><div className="p-6">{messages.length === 0 ? <><p className="max-w-xl text-sm leading-6 text-slate-500">Choose a starting point or ask about a concept, a problem, or your preparation. Your assistant keeps the context academic—and practical.</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{actions.map(([Icon,title,desc]) => <button key={title} onClick={() => setText(title)} className="flex items-start gap-3 rounded-xl border border-slate-200 p-4 text-left transition hover:border-indigo-300 hover:bg-indigo-50"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-indigo-100 text-indigo-600"><Icon size={17}/></span><span><b className="block text-sm text-slate-800">{title}</b><small className="mt-1 block text-xs text-slate-500">{desc}</small></span></button>)}</div></> : <div className="space-y-4">{messages.map((message,i)=><div key={i} className={`max-w-[82%] rounded-2xl px-4 py-3 text-sm leading-6 ${message.user?'ml-auto bg-indigo-600 text-white':'border border-slate-200 bg-slate-50 text-slate-700'}`}>{message.text}</div>)}</div>}</div><form onSubmit={send} className="mx-6 mt-8 flex items-center gap-2 rounded-xl border border-slate-200 bg-slate-50 p-2"><input value={text} onChange={(e)=>setText(e.target.value)} className="min-w-0 flex-1 bg-transparent px-3 py-2 text-sm outline-none" placeholder="Ask anything about your learning..."/><button className="grid h-9 w-9 place-items-center rounded-lg bg-indigo-600 text-white" aria-label="Send"><Send size={16}/></button></form></section></div>;
}
